### ISSUE TITLE
Android server browser

### ISSUE THREAD

**Issue by andy5995** [netpanzer/serverbrowser-js#1]
Might get some ideas from the [android server browser](https://github.com/francov/netPanzerSB) that @francov did. Or maybe test it a bit and ask them if they want to add their repo to this org.

**Comment by winrid** [comment]
Neat!

Note that when the new site is up the master server will be rewritten in Python and save the current servers and player stats in a database. Then, we'll have an API to get player info. This is a more "standard" and reliable way of doing things, IMO. The site will then have a server-browser built in that people can embed via an iframe.
